export default {
  isAuthenticated: window.localStorage.getItem('MY_AUTH_APP'),
  cart: [],
  buyer: [],
  products: [
    {
      id: "1",
      image: "./img/kittie.jpg",
      name: "Camiseta",
      price: 25,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "3",
      image: "./img/another-kittie.jpg",
      name: "Mug",
      price: 10,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "4",
      image: "./img/puppie-hat.jpg",
      name: "Pin",
      price: 4,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "5",
      image: "./img/cup.jpg",
      name: "Stickers",
      price: 2,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "6",
      image: "./img/kittie.jpg",
      name: "Stickers",
      price: 2,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "7",
      image: "./img/puppie.jpg",
      name: "Hoodie",
      price: 35,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "8",
      image: "./img/kittie.jpg",
      name: "Stickers",
      price: 2,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "9",
      image: "./img/puppie-hat.jpg",
      name: "Mug",
      price: 10,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "10",
      image: "./img/another-kittie.jpg",
      name: "Stickers",
      price: 2,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
  ],
};
